services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: pwd
    volumes:
      - ./db/data/:/var/lib/mysql/
      - ./db/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  users:
    build: ./users
    restart: always
    environment:
      DB_HOST: db
    ports:
      - "8082:8082"

  web:
    build: ./web
    ports:
    - "8083:80"

  products:
    build: ./products
    restart: always
    ports:
      - "8084:8084"
