services:

  web:
    depends_on:
      - products
      - users
    image: nginx:1.29.3
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/public:/usr/share/nginx/html

  users:
    build: ./users
    environment:
      DB_HOST: mariadb
    ports:
      - "8081:8081"
    depends_on:
      - mariadb

  mariadb:
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: pwd
    image: mariadb:12.0.2
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/scripts:/docker-entrypoint-initdb.d

  adminer:
    depends_on:
      - mariadb
    image: adminer:5.4.1
    ports:
      - 8090:8080
    restart: unless-stopped

  products:
    build: ./products
    restart: always
    ports:
      - "8083:8083"
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "app"
      MONGO_COLLECTION: "products"
      PORT: "8083"

  mongo:
    image: mongo:8.2.1
    restart: always
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
